In [2]:
import pandas as pd

schools1 = ["michigan-state", "northwestern", "ohio-state"]
schools2 = ["maryland", "michigan", "minnesota"]
schools3 = ["indiana", "illinois", "nebraska"]
schools4 = ["iowa", "penn-state", "purdue"]
schools5 = ["rutgers", "wisconsin"]
years = list(range(2021, 2025))

In [ ]:
for s in schools5:
    winshare = pd.DataFrame()
    for y in years:
        df = pd.read_html(f"https://www.sports-reference.com/cbb/schools/{s}/men/{y}.html")
        data = df[11].iloc[:, [1, 2, 4] + list(range(20, 24))].copy()
        data["Year"] = y - 1
        winshare = pd.concat([winshare, data], ignore_index=True)
            
    winshare.to_csv(f"./ws/{s}_winshare.csv", index=False)
    print(f"{s} finished!")

In [4]:
nba = pd.read_html("https://www.basketball-reference.com/leagues/NBA_2024_per_game.html")
nba = nba[0].iloc[:, [1, 3, 4]]
nba.to_csv("nba.csv", index=False)

,Rk,Player,Age,Team,Pos,G,GS,MP,FG,FGA,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Awards
0,1.0,Joel Embiid,29.0,PHI,C,39.0,39.0,33.6,11.5,21.8,...,2.4,8.6,11.0,5.6,1.2,1.7,3.8,2.9,34.7,AS
1,2.0,Luka Dončić,24.0,DAL,PG,70.0,70.0,37.5,11.5,23.6,...,0.8,8.4,9.2,9.8,1.4,0.5,4.0,2.1,33.9,"MVP-3,CPOY-6,AS,NBA1"
2,3.0,Giannis Antetokounmpo,29.0,MIL,PF,73.0,73.0,35.2,11.5,18.8,...,2.7,8.8,11.5,6.5,1.2,1.1,3.4,2.9,30.4,"MVP-4,DPOY-9,CPOY-12,AS,NBA1"
3,4.0,Shai Gilgeous-Alexander,25.0,OKC,PG,75.0,75.0,34.0,10.6,19.8,...,0.9,4.7,5.5,6.2,2.0,0.9,2.2,2.5,30.1,"MVP-2,DPOY-7,CPOY-3,AS,NBA1"
4,5.0,Jalen Brunson,27.0,NYK,PG,77.0,77.0,35.4,10.3,21.4,...,0.6,3.1,3.6,6.7,0.9,0.2,2.4,1.9,28.7,"MVP-5,CPOY-5,AS,NBA2"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
731,569.0,Ron Harper Jr.,23.0,TOR,PF,1.0,0.0,4.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,2.0,0.0,NaN
732,570.0,Justin Jackson,28.0,MIN,SF,2.0,0.0,0.5,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
733,571.0,Dmytro Skapintsev,25.0,NYK,C,2.0,0.0,1.0,0.0,0.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
734,572.0,Javonte Smart,24.0,PHI,PG,1.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
735,NaN,League Average,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
pd.read_html("https://www.nba.com/players")[0][:5]

,Player,Team,Number,Position,Height,Weight,Last Attended,Country
0,PreciousAchiuwa,NYK,5,F,6-8,243 lbs,Memphis,Nigeria
1,StevenAdams,HOU,12,C,6-11,265 lbs,Pittsburgh,New Zealand
2,BamAdebayo,MIA,13,C-F,6-9,255 lbs,Kentucky,USA
3,OchaiAgbaji,TOR,30,G,6-5,215 lbs,Kansas,USA
4,SantiAldama,MEM,7,F-C,7-0,215 lbs,Loyola-Maryland,Spain